# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pd.options.display.max_rows": "00_core.ipynb",
         "pd.options.display.max_columns": "00_core.ipynb",
         "LOG_MLFLOW": "00_core.ipynb",
         "EXP_NAME": "00_core.ipynb",
         "TARGET": "00_core.ipynb",
         "STATE": "00_core.ipynb",
         "n_estimators": "00_core.ipynb",
         "max_depth": "00_core.ipynb",
         "learning_rate": "00_core.ipynb",
         "features": "00_core.ipynb",
         "raw_train": "00_core.ipynb",
         "raw_test": "00_core.ipynb",
         "df_list": "00_core.ipynb",
         "drop_features": "00_core.ipynb",
         "proc_df_list": "00_core.ipynb",
         "proc_train": "00_core.ipynb",
         "proc_test": "00_core.ipynb",
         "clf": "00_core.ipynb",
         "val_info": "00_core.ipynb",
         "score_mean": "00_core.ipynb",
         "score_std": "00_core.ipynb",
         "importance_df": "00_core.ipynb",
         "get_cabin_info": "01_preprocessing.ipynb",
         "create_features": "01_preprocessing.ipynb",
         "impute_null_values": "01_preprocessing.ipynb",
         "drop_vars": "01_preprocessing.ipynb",
         "create_dumm": "01_preprocessing.ipynb",
         "run": "01_preprocessing.ipynb",
         "save_interim_data": "01_preprocessing.ipynb",
         "seperate_xy": "02_training.ipynb"}

modules = ["core.py",
           "preprocessing.py",
           "training.py"]

doc_url = "https://KaeganCasey.github.io/titanic/"

git_url = "https://github.com/KaeganCasey/titanic/tree/master/"

def custom_doc_links(name): return None
