# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_training.ipynb (unless otherwise specified).

__all__ = ['seperate_xy']

# Cell
def seperate_xy(df, target_col):
        y = df[target_col]
        X = df.drop(target_col, axis=1)
        return X, y